BALTIMORE_COUNTIES = [
  "Allegany County",
  "Anne Arundel County",
  "Baltimore City",
  "Baltimore County",
  "Calvert County",
  "Caroline County",
  "Carroll County",
  "Cecil County",
  "Charles County",
  "Dorchester County",
  "Frederick County",
  "Garrett County",
  "Harford County",
  "Howard County",
  "Kent County",
  "Montgomery County",
  "Prince George's County",
  "Queen Anne's County",
  "St. Mary's County",
  "Somerset County",
  "Talbot County",
  "Washington County",
  "Wicomico County",
  "Worcester County"]

FEEDBACK = [
  "If you added XYZ feature.",
  "Helped me with XYZ.",
  "It showed me how to ...",
  "It did my taxes.",
  "It had XYZ button.",
  "There was an XYZ form.",
  "It displayed a ..."]