BALTIMORE_COUNTIES = [
  "Allegany County",
  "Anne Arundel County",
  "Baltimore City",
  "Baltimore County",
  "Calvert County",
  "Caroline County",
  "Carroll County",
  "Cecil County",
  "Charles County",
  "Dorchester County",
  "Frederick County",
  "Garrett County",
  "Harford County",
  "Howard County",
  "Kent County",
  "Montgomery County",
  "Prince George's County",
  "Queen Anne's County",
  "St. Mary's County",
  "Somerset County",
  "Talbot County",
  "Washington County",
  "Wicomico County",
  "Worcester County"]

FEEDBACK = [
  "It had unicorns.",
  "If you added XYZ feature.",
  "It sliced and diced.",
  "Sorted by cuteness.",
  "Helped me with XYZ.",
  "You implemented an ABC widget.",
  "It showed me a ...",
  "It did my taxes."]