require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CareReceiverProfilesController do

  # This should return the minimal set of attributes required to create a valid
  # CareReceiverProfile. As you add validations to CareReceiverProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CareReceiverProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all care_receiver_profiles as @care_receiver_profiles" do
      care_receiver_profile = CareReceiverProfile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:care_receiver_profiles).should eq([care_receiver_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested care_receiver_profile as @care_receiver_profile" do
      care_receiver_profile = CareReceiverProfile.create! valid_attributes
      get :show, {:id => care_receiver_profile.to_param}, valid_session
      assigns(:care_receiver_profile).should eq(care_receiver_profile)
    end
  end

  describe "GET new" do
    it "assigns a new care_receiver_profile as @care_receiver_profile" do
      get :new, {}, valid_session
      assigns(:care_receiver_profile).should be_a_new(CareReceiverProfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested care_receiver_profile as @care_receiver_profile" do
      care_receiver_profile = CareReceiverProfile.create! valid_attributes
      get :edit, {:id => care_receiver_profile.to_param}, valid_session
      assigns(:care_receiver_profile).should eq(care_receiver_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CareReceiverProfile" do
        expect {
          post :create, {:care_receiver_profile => valid_attributes}, valid_session
        }.to change(CareReceiverProfile, :count).by(1)
      end

      it "assigns a newly created care_receiver_profile as @care_receiver_profile" do
        post :create, {:care_receiver_profile => valid_attributes}, valid_session
        assigns(:care_receiver_profile).should be_a(CareReceiverProfile)
        assigns(:care_receiver_profile).should be_persisted
      end

      it "redirects to the created care_receiver_profile" do
        post :create, {:care_receiver_profile => valid_attributes}, valid_session
        response.should redirect_to(CareReceiverProfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved care_receiver_profile as @care_receiver_profile" do
        # Trigger the behavior that occurs when invalid params are submitted
        CareReceiverProfile.any_instance.stub(:save).and_return(false)
        post :create, {:care_receiver_profile => { "name" => "invalid value" }}, valid_session
        assigns(:care_receiver_profile).should be_a_new(CareReceiverProfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CareReceiverProfile.any_instance.stub(:save).and_return(false)
        post :create, {:care_receiver_profile => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested care_receiver_profile" do
        care_receiver_profile = CareReceiverProfile.create! valid_attributes
        # Assuming there are no other care_receiver_profiles in the database, this
        # specifies that the CareReceiverProfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CareReceiverProfile.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => care_receiver_profile.to_param, :care_receiver_profile => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested care_receiver_profile as @care_receiver_profile" do
        care_receiver_profile = CareReceiverProfile.create! valid_attributes
        put :update, {:id => care_receiver_profile.to_param, :care_receiver_profile => valid_attributes}, valid_session
        assigns(:care_receiver_profile).should eq(care_receiver_profile)
      end

      it "redirects to the care_receiver_profile" do
        care_receiver_profile = CareReceiverProfile.create! valid_attributes
        put :update, {:id => care_receiver_profile.to_param, :care_receiver_profile => valid_attributes}, valid_session
        response.should redirect_to(care_receiver_profile)
      end
    end

    describe "with invalid params" do
      it "assigns the care_receiver_profile as @care_receiver_profile" do
        care_receiver_profile = CareReceiverProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CareReceiverProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => care_receiver_profile.to_param, :care_receiver_profile => { "name" => "invalid value" }}, valid_session
        assigns(:care_receiver_profile).should eq(care_receiver_profile)
      end

      it "re-renders the 'edit' template" do
        care_receiver_profile = CareReceiverProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CareReceiverProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => care_receiver_profile.to_param, :care_receiver_profile => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested care_receiver_profile" do
      care_receiver_profile = CareReceiverProfile.create! valid_attributes
      expect {
        delete :destroy, {:id => care_receiver_profile.to_param}, valid_session
      }.to change(CareReceiverProfile, :count).by(-1)
    end

    it "redirects to the care_receiver_profiles list" do
      care_receiver_profile = CareReceiverProfile.create! valid_attributes
      delete :destroy, {:id => care_receiver_profile.to_param}, valid_session
      response.should redirect_to(care_receiver_profiles_url)
    end
  end

end
